### ISSUE TITLE
2019.05.31 Twitter 大规模封号后，新账号汇总

### ISSUE THREAD

**Issue by Pangu2020together** [ourhimalayas/txt#9]
![guosaid](https://user-images.githubusercontent.com/50340313/58743416-4ef4d980-8420-11e9-8daf-6a9b19def1eb.png)

> 战友千千万，不可能都完全列出来（没被收录的战友请多海涵）
> 但却可以通过以下用户的（被）关注者、转推及推文下的评论回复来继续裂变式关注其他战友
>
> 如有补充，也恳请战友们可以自行注册 Github 账号后在下面直接跟帖
> 可页面内搜索是否已存在，以避免重复（Windows: Ctrl + F | Mac: Command + F）
>
> 请注意，以下主要使用简体中文，可能有部分战友的昵称使用繁体中文
> 以下排名不分先后

* 路德 https://twitter.com/pangukaitiandi
* Sara https://twitter.com/sarawei5
* 细思 https://twitter.com/xiteller
* 曹长青 https://twitter.com/CaoChangqing
* KyleBass https://twitter.com/Jkylebass
* Inty https://twitter.com/IntyMedia
* 虎目观天下 https://twitter.com/x1os2020
* 川普/彭斯/卢比奥 推特中文直译(支持“郭七条”) https://twitter.com/GuoSupporters
* hotmoon https://twitter.com/hotmoonliuye
* 地球之歌 https://twitter.com/songofearth
* 卡丽熙 https://twitter.com/freedom07653147
* 木兰传奇 https://twitter.com/Mulan2020
* 木兰访谈 https://twitter.com/stevenc50982945
* DTLA https://twitter.com/DTinLAC
* MischaEDM https://twitter.com/MischaEDM
* Mischa https://twitter.com/Mischa49567643
* 萤火虫 https://twitter.com/64forgetmenot
* 握拳而立 https://twitter.com/N3e4Q931wntJ2bN
* Andy再开 https://twitter.com/Andy26473514
* 陛下 https://twitter.com/dingguofantang
* 喜马拉雅国际工作站 https://twitter.com/GlobalHimalaya
* 民心向郭 https://twitter.com/__GTL
* 幸福小哥 https://twitter.com/yeydqpKGyaggKXF
* 血拼 https://twitter.com/bJ0VEN4UE2ATlSb
* 哈恩 https://twitter.com/zhangdonghua2
* 记忆小哥 https://twitter.com/YaX5I5H8HOHHuog
* CCP is a Devil! https://twitter.com/CanadaLaoJiang
* 小札 https://twitter.com/suxinPL
* bluesky https://twitter.com/bluesky56853221
* 耿严 https://twitter.com/gengyantalking
* 随便小妹 https://twitter.com/xiao_bian
* 闻贵净界 https://twitter.com/gwg717gwg
* 大笨钟 https://twitter.com/9ZHOL7crJljSQS7
* 大笨钟 https://twitter.com/DBZHHH
* TheFactOfChina https://twitter.com/thefactofchina
* Susan 李 https://twitter.com/susan_li_aus
* 弱阶招然 https://twitter.com/ruojiezhaoran
* Stacy Chen https://twitter.com/bonsandcake
* 小石头2 https://twitter.com/Buu4aYqRFFWN3mI
* 力量小哥 https://twitter.com/IukhHSIC0lGjCeh
* LL.yao2 https://twitter.com/liulangyao777
* 艺术家李金山 https://twitter.com/2020ccpbiwang
* 财经真相 https://twitter.com/caijingxiang
* God of War https://twitter.com/i6qdsbdsbdf
* Maggieli https://twitter.com/2Maggieli
* maggie18 https://twitter.com/maggie140135733
* 亨利小哥 https://twitter.com/2Henglixiaoge
* Delmont https://twitter.com/87rwl
* 北欧弓箭手 https://twitter.com/gong_jenny
* 曾宏 https://twitter.com/realZengHong
* 太子党 https://twitter.com/tzdang10
* 付海波 https://twitter.com/hLt4G8r7tGhXAH4
* 持枪挺郭 https://twitter.com/gansiCCP
* Ray https://twitter.com/AudreyNebula
* 冰心 https://twitter.com/LH121899
* 朴昌海 https://twitter.com/pchxmly2020
* 文琥 https://twitter.com/huwang_86911
* 坚信郭七条不动摇 https://twitter.com/mwww8964_942
* 秋桜（小百合） https://twitter.com/nahanminzhu2018
* 中兴 https://twitter.com/17zhongxing
* 方圆之间 https://twitter.com/Julia720900
* 福安康 https://twitter.com/Ankangshe
* 我们都是郭文贵 https://twitter.com/Ivana_uu
* truth_discovery https://twitter.com/DiscoveryTruth
* Steven https://twitter.com/Steven48526279
* Betty https://twitter.com/bettylong8624
* 华夏小哥 https://twitter.com/Huaxiaxiaoge
* Arthur https://twitter.com/ArthurJ45490660
* SimpleDeeb https://twitter.com/SimpleDeeb
* 弘燚 https://twitter.com/hhh49802017
* 小皮匠 https://twitter.com/xiaopijiang
* 伯多祿 https://twitter.com/xt70610707
* 泰国援郭会 https://twitter.com/guowenguitaiguo
* 黎明曙光MAGA https://twitter.com/QQbianca_88
* 曝光台 https://twitter.com/BGTV02
* 李小牧 https://twitter.com/leekomaki
* 张牧之 https://twitter.com/Warriorsli2017
* 草民看世界 https://twitter.com/manthe3rd1
* 上海维权 https://twitter.com/shanzhai01
* 鲁班七号 https://twitter.com/housanbang
* 跟随英雄走向喜马拉雅 https://twitter.com/liuzw71
* 中国之声 https://twitter.com/ywxk7
* 2017文贵元年 https://twitter.com/Tingguigui2
* harrypotter https://twitter.com/harrypotter3964
* 数据小哥 https://twitter.com/MZ5BqgNgoA0IERk
* 香港人🐜（曉穎） https://twitter.com/wingflyhkg
* 挺郭小蚂蚁 https://twitter.com/tweetery1968
* 香港挺郭后援会 https://twitter.com/TG6UlUmEtXFNRNH
* 文韬武略🐉贵有仁心 https://twitter.com/xinxinzihuo
* 沉默之声（相思小蚂蚁） https://twitter.com/chenmezhisheng
* 习近彭01 https://twitter.com/wakeupfrog01
* 至暗时刻 https://twitter.com/zq0504
* 推特地下党新闻发言人 https://twitter.com/tuituji1
* 战胜邪恶 https://twitter.com/05YNJr8glUNlRIK
* rika https://twitter.com/rika61743477
* 小猫咪 https://twitter.com/zjgzKIE1jZRl2oe
* BO LU 小号 https://twitter.com/BoLu213
* BO LU https://twitter.com/lvbo99
* Micheal https://twitter.com/Micheal47238455
* 心如飞鸟 https://twitter.com/lolococo2018
* 温妮 https://twitter.com/Wendy31476301
* 自由是家 https://twitter.com/luis16354178
* 野良貓 https://twitter.com/PGyRcUIpwY90CYe
* 杀猪的 https://twitter.com/jackdkscn
* 潇潇春雨 https://twitter.com/shFpR2rZDCN8Fb8
* 爆料洪流 https://twitter.com/hongliuli
* Coffee Cantata P.A. https://twitter.com/lattecantata
* 大将军 https://twitter.com/NzDbl
* 老顽童 https://twitter.com/XXIztmAPnH44V14
* 顽童大号 https://twitter.com/Wesleywg87
* 天人合一 https://twitter.com/Sophie518421
* anonymous https://twitter.com/anonymous_adm
* 月均 https://twitter.com/N5hXUWsn554Svne
* 轻烟姐姐 https://twitter.com/Fang6768
* Citizens of the American Republic https://twitter.com/CitizensAR
* 星河(九鼎咸震) https://twitter.com/spvtoo
* 文贵在行动 https://twitter.com/ZecharyZ
* 虎嘯東方2019 https://twitter.com/W9kV5Stx7wANeyb
* 贵在坚持！ https://twitter.com/coleman6064
* 我爱我家 https://twitter.com/TangWen2
* suer https://twitter.com/suer55386087
* 华夏小哥 https://twitter.com/Huaxia_yixiao
* Isky396 https://twitter.com/isky396
* 李倍儿喜 https://twitter.com/Libeixi123
* 邱岳首 https://twitter.com/QYueshou
* 安红 https://twitter.com/jujiangxuan6838
* 超级猎人 https://twitter.com/gyh98878
* 传说中的章鱼帝 https://twitter.com/Eazyyi1
* Steve Yates (葉望輝) https://twitter.com/YatesDCIA
* C.K https://twitter.com/ForceKorea
* 不涵而立 掰白 https://twitter.com/buhanerly190601
* Emilie jiang https://twitter.com/EmilieJiang
* 一直向前！2020 https://twitter.com/hecha042772579
* 天佑文贵 https://twitter.com/OzFzf
* 上進哥又殺回來啦！ https://twitter.com/Jinamerican
* 上进哥2 https://twitter.com/JinJin190531
* 文熊 https://twitter.com/edwardchen7772
* Percy https://twitter.com/Percy33521088
* fengfan01 https://twitter.com/fengfan5201
* USAphilipUSA https://twitter.com/USAphilipUSA
* llyzs https://twitter.com/llyzs
* 还权于民 天下正道 -挺郭战友 https://twitter.com/ChinaRecht
* Z123 https://twitter.com/cnvoice4justice
* 黎哥重生（喜马拉雅小蚂蚁） https://twitter.com/tianxin5212
* Taiwan_Spirit我思故我在 https://twitter.com/SpiritTaiwan
* 文青 https://twitter.com/neilyoung007
* KekeZ(文可) https://twitter.com/Kekexilimeimei2
* Annie （喜马拉雅） https://twitter.com/AnnieZh46987581
* 推推党宣传部长（备用号） https://twitter.com/TWPxuanchuan
* 伊娃 https://twitter.com/MsSg242502
* 挺郭文信 https://twitter.com/tian1cheng
* anne https://twitter.com/anne13812038
* 子弹飞 https://mobile.twitter.com/realzidanfei201
* runrunblue https://twitter.com/2Runrunblue
* 孙宇成 https://twitter.com/SYC99999

![allback](https://user-images.githubusercontent.com/50340313/58743563-887b1400-8423-11e9-9f01-6ad4f4731e79.png)
![assemble](https://user-images.githubusercontent.com/50340313/58743566-8add6e00-8423-11e9-8412-c5b180355e65.png)

> 拓展阅读：[郭文贵爆料革命 · 启蒙开智入门指南 ✊✊✊](https://github.com/ourhimalayas/txt/issues/1)

**Comment by tuxiaomu** [comment]
土小木：
[https://twitter.com/tuxiaomu](https://twitter.com/tuxiaomu)

**Comment by lehr** [comment]
BenKtallmadge
https://mobile.twitter.com/BenKTallmadge

爆料了中共海外高层渗透，有一个长篇thread是卡梅伦和特蕾莎梅内阁收受来自华为和中共的贿赂的（解释了为何英国政府在华为事件上摇摆不定）

**Comment by zhlmir2** [comment]
雪原伞：
https://twitter.com/JnpZ1Je1hNPNs7h

**Comment by change1984** [comment]
又赶上这一轮了，第三次了
https://twitter.com/rybgy

**Comment by tinrach** [comment]
桑梓
@sQn7mGSFecBI6OL

**Comment by chengbj522** [comment]
https://twitter.com/zhongnanhai010

**Comment by fanranxingwu** [comment]
fanranxingwu
https://twitter.com/fanranxingwu1

**Comment by Pangu2020together** [comment]
https://twitter.com/EvertChan1

**Comment by spawnmhsbc** [comment]
posthumus @mhsbc also blocked
https://twitter.com/mhsbc
